<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-13T13:55:19 IST" name="Karthika Practice Suite" finished-at="2021-04-13T13:56:33 IST" duration-ms="74416">
    <groups>
    </groups>
    <test started-at="2021-04-13T13:55:19 IST" name="Karthika Tests" finished-at="2021-04-13T13:56:33 IST" duration-ms="74416">
      <class name="com.athmatest.qa.testcases.SampleTesting">
        <test-method is-config="true" signature="intialization()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:19 IST" name="intialization" finished-at="2021-04-13T13:55:32 IST" duration-ms="12985" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialization -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:32 IST" name="loginToTheApplication" finished-at="2021-04-13T13:55:36 IST" duration-ms="4433" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="myFirstTest()[pri:1, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:36 IST" name="myFirstTest" finished-at="2021-04-13T13:55:36 IST" duration-ms="44" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.athmatest.qa.testcases.SampleTesting.myFirstTest(SampleTesting.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:36 IST" name="logOutFromTheApplication" finished-at="2021-04-13T13:55:41 IST" duration-ms="4486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:41 IST" name="loginToTheApplication" finished-at="2021-04-13T13:55:45 IST" duration-ms="4347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="mySecondTest()[pri:2, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:45 IST" name="mySecondTest" finished-at="2021-04-13T13:55:55 IST" duration-ms="9538" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.athmatest.qa.testcases.SampleTesting.mySecondTest(SampleTesting.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySecondTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:55:55 IST" name="logOutFromTheApplication" finished-at="2021-04-13T13:56:01 IST" duration-ms="6209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:01 IST" name="loginToTheApplication" finished-at="2021-04-13T13:56:05 IST" duration-ms="4363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="myThirdTest()[pri:3, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:05 IST" name="myThirdTest" finished-at="2021-04-13T13:56:13 IST" duration-ms="8155" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.athmatest.qa.testcases.SampleTesting.myThirdTest(SampleTesting.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myThirdTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:13 IST" name="logOutFromTheApplication" finished-at="2021-04-13T13:56:18 IST" duration-ms="4326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:18 IST" name="loginToTheApplication" finished-at="2021-04-13T13:56:22 IST" duration-ms="4366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="myFourthTest()[pri:4, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:22 IST" name="myFourthTest" finished-at="2021-04-13T13:56:28 IST" duration-ms="5881" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFourthTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:28 IST" name="logOutFromTheApplication" finished-at="2021-04-13T13:56:32 IST" duration-ms="4365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.athmatest.qa.testcases.SampleTesting@6d763516]" started-at="2021-04-13T13:56:32 IST" name="closeBrowser" finished-at="2021-04-13T13:56:33 IST" duration-ms="815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.athmatest.qa.testcases.SampleTesting -->
    </test> <!-- Karthika Tests -->
  </suite> <!-- Karthika Practice Suite -->
</testng-results>
